server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: catalogs-service
          uri: http://localhost:5002
          predicates:
            - Path=/api/v1/catalogs, /api/v1/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogServiceCircuitBreaker
                fallbackUri: forward:/fallback/catalogs
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2 # How many requests allowed per second
                redis-rate-limiter.burstCapacity: 4 # Max spike capacity allowed in a single burst
                redis-rate-limiter.requestedTokens: 1 # Tokens consumed per request
                key-resolver: "#{@ipKeyResolver}" # Identifies clients by IP address

        - id: orders-service
          uri: http://localhost:5001
          predicates:
            - Path=/api/v1/orders, /api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orders
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 4
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      catalogServiceCircuitBreaker:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
      orderServiceCircuitBreaker:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
