server:
  port: 5002
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  application:
    name: catalogs-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite_catalogs
    username: quickbite
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: CatalogsHikariPool

  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/quickbite_catalogs
      database: quickbite_catalogs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  jwt:
    secret: 2a48518d7ceebe18b2c0f0e45222d3e956d02824ba4193b30293a60537c8bced9064ead4c1ac0d26
    expiration: 86400000 # 24 Hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # Sample 100% of requests for local development & debugging
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # URL of your local Zipkin container

quickbite:
  rabbitmq:
    catalogs-exchange: catalogs.events
    catalogs-queue: catalogs.item-created.projection-queue
    catalogs-routing-key: catalogs.item.created

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
