server:
  port: 5001

spring:
  application:
    name: orders-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/quickbite_orders
  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite_orders
    username: quickbite
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Actuator & Observability Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0 # Capture 100% of requests during dev
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Trace & Span ID in Logs
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html